### ISSUE TITLE
Populate Error

### ISSUE THREAD

**Issue by thomasdashney** [balderdashy/sails-memory#14]
Is sails-memory fully tested to work with associations?

I'm running into an issue (which works fine when using sails-mysql) where I find() a record, and see the association's id. But when I populate('that association') it populates an associated record with a different id.

Ideas very much appreciated!

**Comment by sgress454** [comment]
@thomasdashney Sorry we never got to this.  `sails-memory` should work just fine with associations; it's essentially identical to `sails-disk`, which is what we use for all of the Sails core tests.  That being said, `sails-memory` does tend to get unfairly neglected, so if you're still working with this and have a reliable way to reproduce the issue, I'll certainly take a look.

**Comment by thomasdashney** [comment]
Thanks for the response! I've actually redesigned my test suite to use a database anyway because that's what's happening in production.
