### ISSUE TITLE
Using sails-memory as a cache

### ISSUE THREAD

**Issue by kokujin** [balderdashy/sails-memory#4]
The docs state that sails-memory should not be used in production, is it viable as a sort of cache? Let me explain. I have a User model  that uses a MongoDB adapter, instead of hitting the database to validate the user for every auth request, I could store a token of an authenticated user in a separate model that uses the memory adapter and access that first before accessing the User model with the mongoDB adapter.

**Comment by camsjams** [comment]
anyone have a partial or skeleton for a `sails-memcache` adapter - I would be interested in using or completing (if someone has started one)
